name: VUnit Tests
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow numpy pathlib scikit-image argparse
      - uses: actions/checkout@v2
      - name: Run reference script
        run: python scripts/edgedetect_reference.py -f assets/leo.jpg
