name: VUnit Tests
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow numpy pathlib scikit-image argparse vunit_hdl
      - uses: actions/checkout@v2

      - name: Create .txt from input img
        run: mkdir -p scripts/vunit_out && python scripts/rgb2txt.py -i assets/leo.jpg -o scripts/vunit_out/input_img.txt

      - name: Run reference script
        run: python scripts/edgedetect_reference.py -f assets/leo.jpg
      - name: Create jpg
        run : python scripts/txt2gray.py -i scripts/vunit_out/sobel_control -o scripts/vunit_out/sobel_control.jpg

      - name: Run VUnit tests
        run: python scripts/run.py

      - name: Archive run results
        uses: actions/upload-artifact@v3
        with:
            name: vunit-out
            path: scripts/vunit_out

