name: VUnit Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install python3
          python -m pip install --upgrade pip
          pip install pillow numpy pathlib scikit-image argparse --no-build-isolation
      - uses: actions/checkout@v2
      - uses: VUnit/vunit_action@v0.1.0
        with:
            run_file: scripts/run.py
