name: VUnit Tests
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow numpy pathlib scikit-image argparse vunit_hdl

      - uses: ghdl/setup-ghdl-ci@nightly
        with:
            backend: mcode

      - uses: actions/checkout@v2

      - name: Run VUnit tests
        run: python scripts/run.py "*gray=True,gauss=True,sobel=True*" -v -o scripts/vunit_out

      - name: Archive run results
        uses: actions/upload-artifact@v3
        with:
            name: vunit-out
            path: scripts/vunit_out

